#!/bin/bash
# Fit the three organ erasers, then drive configs/mil_tasks.txt.
#
# Do NOT edit this file while it is running: bash re-reads the script from the
# current byte offset, so an edit shifts the offsets and execution resumes in the
# middle of a line. That is what killed the previous driver mid-run.
set -uo pipefail
cd "$(dirname "$0")/.."
TASKS=configs/mil_tasks.txt
ACCOUNT=bhwm-delta-gpu
PART=gpuA40x4-interactive,gpuA100x4-interactive
MOD="module load pytorch-conda"
CHUNK=4
R=/work/hdd/bhwm
V=20x_224px_0px_overlap/features_virchow2
# Every cohort root. "The rest" spans all of them, and mu is pooled over
# pos+neg, so the negative set must be resolvable or the fit aborts.
ALLDIRS="$R/trident_features/master_benchmark/$V,$R/PANDA/$V,$R/BRACS/$V,$R/BACH/$V,$R/UBC-OCEAN/$V"

submit_and_wait() {  # name walltime command...
    local name=$1 wt=$2; shift 2
    local jid=""
    for attempt in $(seq 1 240); do
        jid=$(sbatch --parsable --job-name="$name" --output="logs/${name}_%j.log" \
              --account=$ACCOUNT --partition=$PART \
              --mem=200G --cpus-per-task=32 --gpus=4 --nodes=1 --time="$wt" \
              --wrap="$MOD && $*" 2>/dev/null)
        [[ -n "$jid" ]] && break
        sleep 45
    done
    [[ -z "$jid" ]] && { echo "  !! could not submit $name"; return 1; }
    echo "  $name -> $jid"
    while squeue -h -j "$jid" -o "%t" 2>/dev/null | grep -q .; do sleep 30; done
}

echo "== fitting erasers =="
for organ in LUNG BREAST PROSTATE; do
    out=results/unlearners/${organ}_k64.pt
    [[ -f "$out" ]] && { echo "  $organ present"; continue; }
    submit_and_wait "fitU_${organ}" "00:55:00" \
      "python -u scripts/fit_unlearner.py --forget_organ $organ \
       --encoder_dir $ALLDIRS --metadata data/multi_benchmark_metadata.csv \
       --method svd --k 64 --max_slides 1000 --patches_per_slide 64 --output $out"
    # A job leaves squeue before its output is visible on the shared filesystem.
    # Checking immediately declared a COMPLETED fit dead: BREAST_k64.pt existed
    # on disk seconds after the driver had already exited. Poll before giving up.
    for _ in $(seq 1 20); do [[ -f "$out" ]] && break; sleep 5; done
    [[ -f "$out" ]] || { echo "  !! $organ eraser did not appear - stopping"; exit 1; }
done

echo "== running MIL tasks =="
total=$(grep -c . "$TASKS")
off=0
while (( off < total )); do
    left=0
    while read -r t; do
        [[ -z "$t" ]] && continue
        o=$(sed -n 's/.*--output_json \([^ ]*\).*/\1/p' <<<"$t")
        [[ -f "$o" ]] || left=$((left+1))
    done < "$TASKS"
    (( left == 0 )) && { echo "all MIL tasks complete"; break; }
    echo "  offset=$off  ($left of $total missing)"
    submit_and_wait "milq_${off}" "00:55:00" \
        "bash scripts/run_mil_batch.sh $TASKS $off $CHUNK"
    off=$(( off + CHUNK ))
done
echo "MIL DRIVER DONE"
